Repository 9oormthon-univ/2024_DANPOONG_TEAM_11_BE, pull requests merged in 2024-11, with the labels that each got.

#2 chore: 백엔드 프로젝트 초기 설정 및 기본 구조 설정
  NongDam-backend/.gitattributes
  NongDam-backend/.gitignore
  NongDam-backend/build.gradle
  NongDam-backend/gradle/wrapper/gradle-wrapper.jar
  NongDam-backend/gradle/wrapper/gradle-wrapper.properties
  NongDam-backend/gradlew
  NongDam-backend/gradlew.bat
  NongDam-backend/settings.gradle
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/NongDamBackendApplication.java
  NongDam-backend/src/main/resources/application.yml
  NongDam-backend/src/test/java/shop/nongdam/nongdambackend/NongDamBackendApplicationTests.java
Labels: Setting

#5 feat: 커스텀 예외처리 템플릿과 API 응답 템플릿 세팅
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/error/ControllerAdvice.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/error/dto/ErrorResponse.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/error/exception/AccessDeniedGroupException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/error/exception/AuthGroupException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/error/exception/InvalidGroupException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/error/exception/NotFoundGroupException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/template/ApiResponse.java
Labels: Setting

#6 Feature/#3 스웨거세팅
  NongDam-backend/build.gradle
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/config/SwaggerConfig.java
Labels: Feature

#10 feat: QueryDSL 설정 및 의존성 추가
  NongDam-backend/.gitignore
  NongDam-backend/build.gradle
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/config/QuerydslConfig.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/config/SwaggerConfig.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/member/domain/Member.java
Labels: Feature, Setting

#11 feat: 카카오 소셜 로그인 기능 구현
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/api/controller/AuthController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/api/controller/AuthDocs.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/api/dto/request/RefreshTokenRequestDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/api/dto/request/TokenRequestDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/api/dto/response/AccessAndRefreshTokenResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/api/dto/response/IdTokenResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/api/dto/response/KakaoTokenResponse.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/api/dto/response/MemberInfoResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/api/dto/response/MemberLoginResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/application/AuthMemberService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/application/AuthService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/application/AuthServiceFactory.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/application/KakaoAuthService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/application/TokenService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/exception/EmailNotFoundException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/exception/ExistsMemberEmailException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/exception/InvalidTokenException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/exception/OAuthException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/exception/ProviderNotFoundException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/annotation/CurrentMemberEmail.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/annotationresolver/CurrentMemberEmailArgumentResolver.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/config/AppConfig.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/config/FilterWebConfig.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/config/JpaAuditingConfig.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/domain/BaseEntity.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/filter/LogFilter.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/filter/LoginCheckFilter.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/jwt/TokenProvider.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/jwt/api/dto/TokenDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/jwt/domain/Token.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/jwt/domain/repository/TokenRepository.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/template/ApiResponseTemplate.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/member/domain/Member.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/member/domain/Role.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/member/domain/SocialType.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/member/domain/repository/MemberRepository.java
  NongDam-backend/src/main/resources/application.yml
  NongDam-backend/src/test/java/shop/nongdam/nongdambackend/NongDamBackendApplicationTests.java
Labels: Feature

#15 Feature/#7: 역할 필드 추가 및 설명 추가
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/member/domain/Role.java
Labels: Feature

#12 Feature/#9 docker cicd
  .github/workflows/dev-deploy.yml
  .idea/.gitignore
  NongDam-backend/.gitignore
  NongDam-backend/Dockerfile
  NongDam-backend/docker-compose.override.yml
  NongDam-backend/docker-compose.prod.yml
  NongDam-backend/docker-compose.yml
Labels: Feature, Setting, devops

#16 Fix/#7: 이메일 반환하는 어노테이션 오류 해결
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/config/AnnotationWebConfig.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/member/domain/repository/MemberRepository.java
Labels: Bug

#19 Feature/#18: 이미지 업로드 기능 추가
  NongDam-backend/build.gradle
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/config/S3Config.java
  NongDam-backend/src/main/resources/application.yml
Labels: Feature

#20 Feature/#13 farm signup 농가 회원가입 및 조회
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/api/controller/FarmController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/api/controller/FarmDocs.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/api/dto/request/FarmSaveRequestDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/api/dto/response/FarmInfoResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/api/dto/response/FarmInfoResponseDTOs.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/application/FarmService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/domain/Farm.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/domain/repository/FarmCustomRepository.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/domain/repository/FarmCustomRepositoryImpl.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/domain/repository/FarmRepository.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/exception/FarmAlreadyExistException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/exception/FarmNotFoundException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/region/domain/Region.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/region/domain/repository/RegionRepository.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/region/exception/RegionNotFoundException.java
  NongDam-backend/src/main/resources/application.yml
  NongDam-backend/src/main/resources/data.sql
Labels: Feature

#26 Feature/#24 farm badge 농가 뱃지
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/api/controller/FarmController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/api/controller/FarmDocs.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/api/dto/response/FarmBadgeResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/api/dto/response/FarmDetailInfoResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/application/FarmService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/domain/Farm.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/domain/FarmBadge.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/domain/FarmBadgeAssignment.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/domain/FarmBadgeAssignmentId.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/domain/repository/FarmBadgeRepository.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/farm/exception/FarmBadgeNotFoundException.java
  NongDam-backend/src/main/resources/data.sql
Labels: Feature

#28 Refactor/#27: 스웨거 설정 변경
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/config/SwaggerConfig.java
  NongDam-backend/src/main/resources/application.yml
Labels: Refactor

#31 Fix/#22: 식당 등록 안되는 문제 해결
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/controller/RestaurantController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/dto/request/RestaurantDetailSaveRequestDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/dto/request/RestaurantUpdateRequestDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/dto/response/RestaurantInfoResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/appllication/RestaurantService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/api/dto/request/MenuSaveRequestDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/api/dto/request/MenuSaveRequestDTOs.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/application/MenuService.java
Labels: Bug

#30 feat: 식료품 이미지 추가
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/api/controller/IngredientController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/api/controller/IngredientDocs.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/api/dto/response/IngredientInfoResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/application/IngredientService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/domain/Ingredient.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/domain/IngredientImage.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/domain/IngredientReview.java
Labels: Feature

#33 Refactor/#22: 식당 메뉴 등록시 농산물 등록
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/application/MenuService.java
Labels: Refactor

#34 fix/#22: 식당 메뉴 등록 시 메뉴 등록 안되는 오류 해결
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/api/dto/response/MenuInfoResponseDTO.java
Labels: Bug

#35 fix: 식당 등록 안되는 문제 해결
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/domain/Restaurant.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/api/controller/MenuDocs.java
Labels: Bug

#36 Feat: 식당 주의사항 필드 추가
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/dto/request/RestaurantDetailSaveRequestDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/dto/response/RestaurantDetailInfoResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/dto/response/RestaurantInfoResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/appllication/RestaurantService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/domain/Restaurant.java
Labels: Feature

#37 refactor: 식당 정보 반환 시 모든 메뉴 반환하도록 변경
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/controller/RestaurantController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/controller/RestaurantDocs.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/dto/response/RestaurantInfoResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/appllication/RestaurantService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/api/dto/request/MenuSaveRequestDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/api/dto/response/MenuInfoResponseDTOs.java
Labels: Refactor

#38 refactor: 식당 전체 조회 시 상세정보 작성한 식당만 조회가능하도록 수정
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/controller/RestaurantController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/controller/RestaurantDocs.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/dto/response/RestaurantTagResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/dto/response/RestaurantTagResponseDTOs.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/appllication/RestaurantService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/domain/Restaurant.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/domain/repository/RestaurantCustomRepository.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/domain/repository/RestaurantCustomRepositoryImpl.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/exception/MenuNotFoundException.java
Labels: Refactor

#39 refactor: 메뉴 등록 시 농산물 이미지 추가
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/dto/response/RestaurantDetailInfoResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/api/controller/MenuController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/api/controller/MenuDocs.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/api/dto/response/MenuInfoResponseDTO.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/application/MenuService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/domain/Menu.java
Labels: Refactor

#44 Feature/#42: Role에 따라 접근할 수 있는 api 제한하는 기능 추가
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/auth/application/TokenService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/annotation/AuthorizeRole.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/annotationresolver/RoleCheckInterceptor.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/config/AnnotationWebConfig.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/jwt/TokenProvider.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/api/controller/IngredientController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/member/exception/RoleAccessDeniedException.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/api/controller/RestaurantController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/restaurant/menu/api/controller/MenuController.java
Labels: Feature

#45 Feature/#43 gpt
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/global/config/OpenAiConfig.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/api/controller/IngredientController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/api/dto/response/IngredientGptCommentDto.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/application/IngredientService.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/domain/Ingredient.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/ingredient/domain/IngredientImage.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/openai/api/controller/OpenAiController.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/openai/api/dto/Message.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/openai/api/dto/request/ChatGPTRequest.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/openai/api/dto/response/ChatGPTResponse.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/openai/application/IngredientAnalysisScript.java
  NongDam-backend/src/main/java/shop/nongdam/nongdambackend/openai/application/OpenAiService.java
  NongDam-backend/src/main/resources/application.yml
Labels: Feature
